# docker-compose.staging.yml
# Usar na VPS staging com: docker compose -f docker-compose.yml -f docker-compose.staging.yml up -d

services:
  frontend:
    container_name: fe-aponta-staging
    networks:
      - aponta-network

networks:
  aponta-network:
    external: true
    name: api-aponta-vps_default
