name: aponta-prod-frontend

services:
  fe-aponta-prod:
    image: ghcr.io/pedroct/aponta-sefaz-frontend/fe-aponta:latest
    container_name: fe-aponta-prod
    restart: unless-stopped
    environment:
      - TZ=America/Fortaleza
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - aponta-shared-network

networks:
  aponta-shared-network:
    external: true
    name: aponta-shared-network
