# docker-compose.prod.yml
# Override para VPS produção
# Uso: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build

services:
  frontend:
    container_name: fe-aponta-prod
    ports:
      - "3000:80"

networks:
  aponta-network:
    external: true
    name: aponta-shared-network
