# docker-compose.prod.yml
# Usar na VPS produção com: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  frontend:
    container_name: fe-aponta-prod
    networks:
      - aponta-network

networks:
  aponta-network:
    external: true
    name: api-aponta-vps_default
