name: aponta-prod-frontend

services:
  frontend:
    image: ghcr.io/pedroct/aponta-sefaz-frontend/fe-aponta:latest
    build: null
    container_name: fe-aponta-prod
    ports: []
    networks:
      - aponta-shared-network

networks:
  aponta-shared-network:
    external: true
    name: aponta-shared-network
